server:
  port: 8050

spring:
  application:
    name: maple-manager
  cache:
    type: redis
  redis:
    # cluster:
    #   nodes:
    #   max-redirects:
    host: localhost
    port: 6379
    lettuce:
      pool:
        max-active: 8
        max-wait: -1ms
        max-idle: 8
        min-idle: 0

feign:
  okhttp:
    enabled: true

maple:
  manager:
    consume-job: true
    consume-job-period: 6000
    refresh-yarn: false
    yarn-refresh-period: 60000
    refresh-k8s: true
    k8s-refresh-period: 10000
