###

POST http://localhost:10001/api/jdbc/dbs
Content-Type: application/json
Accept: application/json

{
  "url": "jdbc:postgresql://localhost:5432/maple",
  "username": "xi_root",
  "password": "123456",
  "driverClassName": "org.postgresql.Driver"
}

###

POST http://localhost:10001/api/jdbc/schemas
Content-Type: application/json
Accept: application/json

{
  "url": "jdbc:postgresql://localhost:5432/maple",
  "username": "xi_root",
  "password": "123456",
  "driverClassName": "org.postgresql.Driver",
  "databaseName": "maple"
}

###

POST http://localhost:10001/api/jdbc/tables
Content-Type: application/json
Accept: application/json

{
  "url": "jdbc:postgresql://localhost:5432/maple",
  "username": "xi_root",
  "password": "123456",
  "driverClassName": "org.postgresql.Driver",
  "databaseName": "maple",
  "schemaName": "public"
}

###

POST http://localhost:10001/api/jdbc/table
Content-Type: application/json
Accept: application/json

{
  "url": "jdbc:postgresql://localhost:5432/maple",
  "username": "xi_root",
  "password": "123456",
  "driverClassName": "org.postgresql.Driver",
  "databaseName": "maple",
  "schemaName": "public",
  "tableName": "maple_user"
}