eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/ # 指定 Eureka Server 的地址
    register-with-eureka: true # 是否注册自己到 Eureka Server，默认为 true
    fetch-registry: true # 是否从 Eureka Server 获取注册表信息，默认为 true
  instance:
    prefer-ip-address: true # 使用 IP 地址而不是主机名进行注册，默认为 false
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port} # 设置实例 ID，默认是主机名和端口

server:
  port: 6081
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  main:
    allow-bean-definition-overriding: true # 是否允许覆盖已定义的 Bean
  application:
    name: maple-mp-service
  jackson:
    date-format: java.text.SimpleDateFormat
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 256MB
  datasource:
    url: jdbc:mysql://localhost:3306/maple?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&rewriteBatchedStatements=true&useServerPrepStmts=true&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=Asia/Shanghai
    username: xi_root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  cache:
    type: redis
  redis:
    # cluster:
    #   nodes:
    #   max-redirects:
    host: localhost
    port: 6379
    lettuce:
      pool:
        max-active: 8
        max-wait: -1ms
        max-idle: 8
        min-idle: 0

mybatis:
  type-aliases-package: org.xi.maple.persistence.persistence.mapper
  mapper-locations: classpath:mapper/*.xml
  configuration:
    cache-enabled: false
    lazy-loading-enabled: false
    multiple-result-sets-enabled: true
    use-column-label: true
    use-generated-keys: false
    default-executor-type: simple
    default-statement-timeout: 25000
    map-underscore-to-camel-case: true
    call-setters-on-nulls: true

pagehelper:
  reasonable: true
  params: "count=countSql"
  support-methods-arguments: true

info:
  app:
    name: ${spring.application.name}

maple:
  aspect:
    controller-method-pattern: "execution(public * org.xi.maple.mp.controller..*.*(..))"
  json-format:
    date-time-format: yyyy-MM-dd HH:mm:ss
    date-format: yyyy-MM-dd
    time-format: HH:mm:ss


freemarker:
  template:
    path: /home/xi/Projects/github/maple/maple-mp-service/src/main/resources