server:
  port: 8050

spring:
  application:
    name: maple-scheduler
  cache:
    type: redis
  redis:
    # cluster:
    #   nodes:
    #   max-redirects:
    host: localhost
    port: 6379
    lettuce:
      pool:
        max-active: 8
        max-wait: -1ms
        max-idle: 8
        min-idle: 0

feign:
  okhttp:
    enabled: true