server:
  port: 10000

spring:
  application:
    name: maple-hadoop-api

maple:
  hdfs:
    username: hadoop
    conf:
      'fs.defaultFS': hdfs://hadoop-cluster
      'dfs.nameservices': hadoop-cluster
      'dfs.ha.namenodes.hadoop-cluster': nn1,nn2
      'dfs.namenode.rpc-address.hadoop-cluster.nn1': hadoop-01:8020
      'dfs.namenode.rpc-address.hadoop-cluster.nn2': hadoop-02:8020
      'dfs.client.failover.proxy.provider.hadoop-cluster': org.apache.hadoop.hdfs.server.namenode.ha.ConfiguredFailoverProxyProvider

feign:
  okhttp:
    enabled: true