spring:
  datasource:
    url: jdbc:mysql://localhost:3306/maple?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&rewriteBatchedStatements=true&useServerPrepStmts=true&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=Asia/Shanghai
    username: xi_root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

generator:
  encoding: UTF-8
  table-name-match-regex: '(?<=maple_).*'
  paths:
    template: ./template/                       # 模版路径
    out: ../                                    # 输出路径
  files:
    ignore: include/, .DS_Store
    aggregate: src/router/index.ts.ftl, views/Home.vue, .env, .env.development, .env.production, .env.test
    copy: public/favicon.ico, public/index.html, src/assets/, src/components/, src/composables/, src/mixin/, src/store/, src/utils/, src/App.vue, src/base_config.js, src/main.js, .browserslistrc, .eslintrc.js, .gitignore, babel.config.js, package.json, tsconfig.json, vue.config.js

  columns:
    base:
      column-name-set: deleted, create_user, update_user, create_time, update_time
      table-name: maple_datasource_type
    not-required:
      - column-name-set: create_time, update_time
#    img-url:
#    video-url:
#    doc-url:
#    page-url:
#    other-url:
    fk-select:
      - column-name-set: datasource_type
        table-name: maple_datasource
        fk:
          foreign-table-name: maple_datasource_type
          value-column-name: type_name
          text-column-name: type_code
    content:
      - column-name-set: datasource_config
        table-name: maple_datasource
      - column-name-set: configuration, exec_info
        table-name: maple_engine_execution_ext_info
      - column-name-set: ext_info

    valid-status:
      - column-name-set: deleted
        status:
          valid: 0
          invalid: 1

  # 公共自定义属性
  common-properties:
    projectName: maple
    module: persistence
    serviceApplicatioName: MapleDatasourceApplication
    servicePort: 8082
    modulePackage: org.xi.maple.persistence
    commonPackage: org.xi.maple.common

    author: 郗世豪（rarexixi@gmail.com）
    javaSrc: src/main/java
    javaTestSrc: src/test/java
    resourcesSrc: src/main/resources

  # 获取数据映射关系
  data-type-map:
    tinyint: Integer
    smallint: Integer
    int: Integer
    'unsigned int': Long
    bigint: Long
    float: Float
    double: Double
    decimal: BigDecimal
    numeric: BigDecimal
    bit: Boolean
    character: Character
    varchar: String
    char: String
    text: String
    tinytext: String
    mediumtext: String
    longtext: String
    blob: byte[]
    tinyblob: byte[]
    mediumblob: byte[]
    longblob: byte[]
    date: LocalDate
    datetime: LocalDateTime
    timestamp: LocalDateTime
