###
POST http://localhost:8080/execution/exec-now?timestamp=0&secret=
Content-Type: application/json

{
  "execFile": "hdfs:///spark3/spark-examples_2.12-3.3.2.jar",
  "fromApp":  "schedule",
  "jobId": "1",
  "bizId":  "1",
  "execUniqId": "7",
  "execName":  "测试执行",
  "cluster": "hadoop-default",
  "resourceGroup":  "default",
  "engineCategory": "spark",
  "engineVersion":  "3.3.2",
  "priority": 1,
  "priUpgradable":  false,
  "group": "schedule-manager",
  "user":  "xishihao",
  "clusterAppId": "",
  "configuration":  "{\"driverCores\":1,\"driverMemory\":\"4g\",\"numExecutors\":2,\"executorCores\":2,\"executorMemory\":\"8g\",\"driverJavaOptions\":\"\",\"driverClassPath\":\"\",\"jars\":\"\",\"files\":\"\",\"archives\":\"\",\"conf\":{\"spark.hadoop.ipc.client.connect.timeout\":3000,\"spark.hadoop.yarn.client.failover-max-attempts\":2},\"runType\":\"jar\",\"runConf\":{\"mainClass\":\"org.apache.spark.examples.SparkPi\",\"args\":\"10\"}}"
}

###

POST http://localhost:8110/execution/exec-now
Content-Type: application/json

{
    "id": 3,
    "uniqueId": "3",
    "execName": "test-xi",
    "execComment": "测试作业",
    "contentType": "path",
    "contentPath": "path",
    "fromApp": "schedule",
    "cluster": "hadoop",
    "clusterQueue": "default",
    "engineCategory": "spark",
    "engineVersion": "3.3.2",
    "priority": 1,
    "runPriority": 1,
    "status": "ACCEPTED",
    "group": "group1",
    "user": "",
    "startTime": null,
    "endTime": null,
    "heartbeatTime": null,
    "createTime": "2023-11-14 10:58:18",
    "updateTime": "2023-11-14 10:58:18",
    "clusterCategory": "YARN",
    "execContent": null,
    "configuration": "{}",
    "extInfo": "{}",
    "execInfo": null
}

###

GET http://localhost:8100/engine-execution/detail?id=3
Content-Type: application/json

###
