###
POST http://{{domain}}/engine-execution/submit
Content-Type: application/json

{
  "uniqueId": "6",
  "execName": "test-xi",
  "execComment": "测试作业",
  "contentType": "path",
  "contentPath": "path",
  "fromApp": "schedule",
  "cluster": "hadoop",
  "clusterQueue": "default",
  "engineCategory": "spark",
  "engineVersion": "3.3.2",
  "priority": 1,
  "group": "group1",
  "user": "",
  "webhooks": "",
  "configuration": "{}",
  "extInfo": "{}"
}

###

GET http://172.21.216.15:8088/ws/v1/cluster/apps?applicationTags=linkis
Content-Type: application/json


###
