###
GET http://localhost:8085/list

###
GET http://localhost:8085/list
token: eyJhbGciOiJSUzI1NiJ9.eyJ1c2VybmFtZSI6InVzZXJuYW1lIiwic3ViIjoiMSIsImlhdCI6MTczMzE0MDkyOSwiZXhwIjoxNzMzMTQ0NTI5fQ.jlfFmtNJ90iTawdUwnOfT9qXbzkbe90DzbiOx_vU9xF4GsrbeQ_V0zFDSHk8hMIzCMo5kbuEpIrxfkZSgDzfjB2fouYjKLYPQaDoO-Dastkwdk4GyuLhp3ZIgnRqg3a6YJm2IOUBJrQfS2oh7X5ZAa9IpFaPzEmWEzrUEZJ8-M6AMay55cXfIquxmVmKHznWM68SYK-Rc96oHvR4n7lBWmG28h09TVK5x0hcUWMCDsr51fhgolO0NI1NhCs7rPqqsne-wZuJVH3kWMCdBclJNd5NZ_IkMKz1urxszi-ttQv7fclCMVOYcs6OBVD5a0qllrduIdiFr5CMEgxqOzbxsQ

###
GET http://localhost:8085/user/1/permissions

###
GET http://localhost:8085/user/1/permissions
token: eyJhbGciOiJSUzI1NiJ9.eyJ1c2VybmFtZSI6InVzZXJuYW1lIiwic3ViIjoiMSIsImlhdCI6MTczMzE0MDkyOSwiZXhwIjoxNzMzMTQ0NTI5fQ.jlfFmtNJ90iTawdUwnOfT9qXbzkbe90DzbiOx_vU9xF4GsrbeQ_V0zFDSHk8hMIzCMo5kbuEpIrxfkZSgDzfjB2fouYjKLYPQaDoO-Dastkwdk4GyuLhp3ZIgnRqg3a6YJm2IOUBJrQfS2oh7X5ZAa9IpFaPzEmWEzrUEZJ8-M6AMay55cXfIquxmVmKHznWM68SYK-Rc96oHvR4n7lBWmG28h09TVK5x0hcUWMCDsr51fhgolO0NI1NhCs7rPqqsne-wZuJVH3kWMCdBclJNd5NZ_IkMKz1urxszi-ttQv7fclCMVOYcs6OBVD5a0qllrduIdiFr5CMEgxqOzbxsQ

###
POST http://localhost:8085/user/login
Content-Type: application/json
Accept: application/json

{
    "username": "admin",
    "password": "admin"
}

###

GET http://localhost:8080/execution/detail?id=1
Content-Type: application/json
Accept: application/json
maple-tag: maple-persistence-service:test-xi

###

GET http://localhost:8082/test/1
Content-Type: application/json
Accept: application/json

###

GET http://localhost:8082/test/list/str
Content-Type: application/json
Accept: application/json

###

PATCH http://localhost:8100/api/applications/enable/1
Content-Type: application/json
Accept: application/json


###

DELETE http://localhost:8082/test/1,2,3
Content-Type: application/json
Accept: application/json

{
  "age": 12
}

###

POST http://localhost:8082/test
Content-Type: application/json
Accept: application/json

{
  "age": 12
}

###

PUT http://localhost:8082/test
Content-Type: application/json
Accept: application/json

{
  "id": 1,
  "age": 1
}

###



PATCH http://localhost:8082/test
Content-Type: application/json
Accept: application/json

{
  "age": 1
}



###

POST http://localhost:10001/dbs
Content-Type: application/json
Accept: application/json

{
  "url": "jdbc:postgresql://localhost:5432/maple",
  "username": "xi_root",
  "password": "123456",
  "driverClassName": "org.postgresql.Driver"
}

###

POST http://localhost:10001/schemas
Content-Type: application/json
Accept: application/json

{
  "url": "jdbc:postgresql://localhost:5432/maple",
  "username": "xi_root",
  "password": "123456",
  "driverClassName": "org.postgresql.Driver",
  "databaseName": "maple"
}

###

POST http://localhost:10001/tables
Content-Type: application/json
Accept: application/json

{
  "url": "jdbc:postgresql://localhost:5432/maple",
  "username": "xi_root",
  "password": "123456",
  "driverClassName": "org.postgresql.Driver",
  "databaseName": "maple",
  "schemaName": "public"
}

###

POST http://localhost:10001/table
Content-Type: application/json
Accept: application/json

{
  "url": "jdbc:postgresql://localhost:5432/maple",
  "username": "xi_root",
  "password": "123456",
  "driverClassName": "org.postgresql.Driver",
  "databaseName": "maple",
  "schemaName": "public",
  "tableName": "maple_user"
}


###

POST http://localhost:10001/dbs
Content-Type: application/json
Accept: application/json

{
  "url": "jdbc:mysql://localhost:3306/maple",
  "username": "xi_root",
  "password": "123456",
  "driverClassName": "com.mysql.cj.jdbc.Driver"
}

###

POST http://localhost:10001/schemas
Content-Type: application/json
Accept: application/json

{
  "url": "jdbc:mysql://localhost:3306/maple",
  "username": "xi_root",
  "password": "123456",
  "driverClassName": "com.mysql.cj.jdbc.Driver",
  "databaseName": "maple"
}

###

POST http://localhost:10001/tables
Content-Type: application/json
Accept: application/json

{
  "url": "jdbc:mysql://localhost:3306/maple",
  "username": "xi_root",
  "password": "123456",
  "driverClassName": "com.mysql.cj.jdbc.Driver",
  "databaseName": "maple",
  "schemaName": "public"
}

###

POST http://localhost:10001/table
Content-Type: application/json
Accept: application/json

{
  "url": "jdbc:mysql://localhost:3306/maple",
  "username": "xi_root",
  "password": "123456",
  "driverClassName": "com.mysql.cj.jdbc.Driver",
  "databaseName": "maple",
  "schemaName": "public",
  "tableName": "maple_user"
}
