server:
  port: 8100
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: maple-persistence-service
  cache:
    type: redis
  redis:
    # cluster:
    #   nodes:
    #   max-redirects:
    host: localhost
    port: 6379
    lettuce:
      pool:
        max-active: 8
        max-wait: -1ms
        max-idle: 8
        min-idle: 0
  jackson:
    date-format: java.text.SimpleDateFormat

  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 256MB

# region datasoruce
  datasource:
    url: jdbc:mysql://localhost:3306/maple?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&rewriteBatchedStatements=true&useServerPrepStmts=true&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=Asia/Shanghai
    username: xi_root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
# endregion
management:
  endpoints:
    # 关闭所有的检查项
    enabled-by-default: false
    web:
      exposure:
        # 暴露监控接口，*为全部接口
        include: 'prometheus'
      ## 省掉了/actuator前缀
      base-path: "/"
  # 对外暴露prometheus接口并显示更多健康信息
  endpoint:
    prometheus:
      enabled: true
    health:
      show-details: always
  ## 关闭内置的检查项
  metrics:
    enable:
      jvm: true
      logback: false
      files: false
      tomcat: false
      executor: false
      disk: false
      uptime: false
      integration: false
# region mybatis
mybatis:
  type-aliases-package: org.xi.maple.persistence.persistence.mapper
  mapper-locations: classpath:mapper/*.xml
  configuration:
    cache-enabled: false
    lazy-loading-enabled: false
    multiple-result-sets-enabled: true
    use-column-label: true
    use-generated-keys: false
    default-executor-type: simple
    default-statement-timeout: 25000
    map-underscore-to-camel-case: true
    call-setters-on-nulls: true
# endregion

# region pagehelper
pagehelper:
  reasonable: true
  params: "count=countSql"
  support-methods-arguments: true
# endregion

# /actuator/info
info:
  app:
    name: ${spring.application.name}

maple:
  json-format:
    date-time-format: yyyy-MM-dd HH:mm:ss
    date-format: yyyy-MM-dd
    time-format: HH:mm:ss