server:
  port: 8082
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  application:
    name: maple-persistence-service
  cache:
    type: redis
  redis:
    # cluster:
    #   nodes:
    #   max-redirects:
    host: localhost
    port: 6379
    lettuce:
      pool:
        max-active: 8
        max-wait: -1ms
        max-idle: 8
        min-idle: 0
  jackson:
    date-format: java.text.SimpleDateFormat

  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 256MB

# region datasoruce
  datasource:
    url: jdbc:mysql://localhost:3306/maple?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&rewriteBatchedStatements=true&useServerPrepStmts=true&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=Asia/Shanghai
    username: xi_root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
# endregion

# region mybatis
mybatis:
  type-aliases-package: org.xi.maple.persistence.persistence.mapper
  mapper-locations: classpath:mapper/*.xml
  configuration:
    cache-enabled: false
    lazy-loading-enabled: false
    multiple-result-sets-enabled: true
    use-column-label: true
    use-generated-keys: false
    default-executor-type: simple
    default-statement-timeout: 25000
    map-underscore-to-camel-case: true
    call-setters-on-nulls: true
# endregion

# region pagehelper
pagehelper:
  reasonable: true
  params: "count=countSql"
  support-methods-arguments: true
# endregion

# /actuator/info
info:
  app:
    name: ${spring.application.name}