eureka:
  instance:
    metadata-map:
      maple-tag: mysql
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/

server:
  port: 10002

spring:
  application:
    name: maple-jdbc-service

maple:
  jdbc:
    get-databases-sql:
      SELECT SCHEMA_NAME AS `databaseName`
      FROM information_schema.SCHEMATA
      WHERE SCHEMA_NAME NOT IN ('mysql', 'information_schema', 'performance_schema')
      ORDER BY SCHEMA_NAME
    get-schemas-sql:
    get-tables-sql: |
      SELECT TABLE_NAME    AS `tableName`,
             TABLE_COMMENT AS `tableComment`
      FROM information_schema.TABLES
      WHERE TABLE_SCHEMA = :databaseName
        AND TABLE_TYPE = 'BASE TABLE'
      ORDER BY TABLE_NAME
    get-table-columns-sql:
      SELECT COLUMN_NAME      AS `columnName`,
             DATA_TYPE        AS `dataType`,
             COLUMN_COMMENT   AS `columnComment`,
             ORDINAL_POSITION AS `columnPosition`,
             CASE WHEN COLUMN_TYPE IN ('tinyint(1)', 'bit(1)') THEN 'BOOLEAN'
                  WHEN DATA_TYPE = 'tinyint' AND COLUMN_TYPE NOT LIKE '%unsigned%' THEN 'TINYINT'
                  WHEN (DATA_TYPE = 'smallint' AND COLUMN_TYPE NOT LIKE '%unsigned%') OR (DATA_TYPE = 'tinyint' AND COLUMN_TYPE LIKE '%unsigned%') THEN 'SMALLINT'
                  WHEN (DATA_TYPE IN ('int', 'mediumint') AND COLUMN_TYPE NOT LIKE '%unsigned%') OR (COLUMN_TYPE = 'smallint' AND COLUMN_TYPE LIKE '%unsigned%') THEN 'INT'
                  WHEN (DATA_TYPE = 'bigint' AND COLUMN_TYPE NOT LIKE '%unsigned%') OR (COLUMN_TYPE IN ('int', 'mediumint') AND COLUMN_TYPE LIKE '%unsigned%') THEN 'BIGINT'
                  WHEN (COLUMN_TYPE = 'bigint' AND COLUMN_TYPE LIKE '%unsigned%') THEN 'DECIMAL(20, 0)'
                  WHEN DATA_TYPE = 'float' THEN 'FLOAT'
                  WHEN DATA_TYPE = 'decimal' AND NUMERIC_PRECISION <= 38 THEN CONCAT('DECIMAL(', NUMERIC_PRECISION, ', ', NUMERIC_SCALE, ')')
                  WHEN DATA_TYPE = 'decimal' AND NUMERIC_PRECISION > 38 THEN 'STRING'
                  WHEN DATA_TYPE = 'date' THEN 'DATE'
                  WHEN DATA_TYPE IN ('time', 'timestamp', 'char', 'varchar', 'binary', 'varbinary') THEN UPPER(COLUMN_TYPE)
                  WHEN DATA_TYPE = 'datetime' THEN CONCAT('TIMESTAMP(', DATETIME_PRECISION, ')')
                  WHEN DATA_TYPE = 'bit' THEN CONCAT('BINARY(', CEIL((NUMERIC_PRECISION + 7) / 8), ')')
                  WHEN DATA_TYPE IN ('tinytext', 'text', 'mediumtext', 'longtext', 'enum', 'json') THEN 'STRING'
                  WHEN DATA_TYPE IN ('tinyblob', 'blob', 'mediumblob', 'longblob') THEN 'BYTES'
                  WHEN DATA_TYPE = 'year' THEN 'INT'
                  WHEN DATA_TYPE = 'set' THEN 'ARRAY<STRING>'
                  ELSE 'STRING' END AS `flinkDataType`
      FROM information_schema.COLUMNS
      WHERE TABLE_SCHEMA = :databaseName
        AND TABLE_NAME = :tableName
        AND DATA_TYPE<>'unspecified'
      ORDER BY ORDINAL_POSITION
    get-table-pk-columns-sql: |
      SELECT COLUMN_NAME      AS `columnName`,
             ORDINAL_POSITION AS `columnPosition`
      FROM information_schema.KEY_COLUMN_USAGE
      WHERE CONSTRAINT_SCHEMA = :databaseName
        AND TABLE_NAME = :tableName
        AND CONSTRAINT_NAME = 'PRIMARY'
      ORDER BY ORDINAL_POSITION;
