server:
  port: 8110
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  application:
    name: maple-execution-manager-service
  jackson:
    date-format: java.text.SimpleDateFormat

plugin: 
  home: ./tmp
  ftl-path: ./tmp

execution:
  exec-home: ./history

feign:
  okhttp:
    enabled: true

# /actuator/info
info:
  app:
    name: ${spring.application.name}
